### ISSUE TITLE
helm-ag does not work when spaces in search term

### ISSUE THREAD

**Issue by jeeger** [syohex/emacs-helm-ag#78] opened 2015-03-17 15:47 UTC
When I do M-x helm-ag, and then enter something like "search term" (without the quotes), I get the message "Failed: 'term'". How can I fix this? Is there a correct way to enter spaces in the search term?

**Comment by alpha22jp** [comment] 2015-03-18 01:37
I was just going to raise the same issue. This problem appears to be caused by `helm-ag--parse-quey` function where the input string is unquoted and split into multiple arguments. It can be fixed by not calling this function as below.

```helm-ag.el.patch
--- a/helm-ag.el
+++ b/helm-ag.el
@@ -145,7 +145,7 @@ They are specified to `--ignore' options."
                                       helm-ag-ignore-patterns))))
     (when helm-ag-use-grep-ignore-list
       (setq args (append args (helm-ag--grep-ignore-list-to-options))))
-    (setq args (append args (helm-ag--parse-query helm-ag--last-query)))
+    (setq args (append args (list helm-ag--last-query)))
     (when this-file
       (setq args (append args (list this-file))))
     (cons command args)))
```

Is this function necessary for some reason?

**Comment by syohex** [comment] 2015-03-18 04:31
@jeeger @alpha22jp  Thanks for reporting issue. I fixed bug about this issue and improve it.
Please check latest version. Here is animation gif with latest version of `helm-ag`.

![helm-ag-has-spaces](https://cloud.githubusercontent.com/assets/554281/6702701/e4919dca-cd72-11e4-85b7-2ec905adc5d7.gif)

**Comment by syohex** [comment] 2015-03-18 04:33
Sorry it still has bug. Please wait.

**Comment by syohex** [comment] 2015-03-18 04:46
I fixed issue when query has dash at #80.

![helm-ag-has-dash](https://cloud.githubusercontent.com/assets/554281/6702846/32418f06-cd75-11e4-9a86-bc4506d29943.gif)

**Comment by alpha22jp** [comment] 2015-03-18 15:47
Works fine, thanks :smile:

But give me a chance to see why `helm-ag--parse-query` is needed. Is it intended to pass some options with search pattern? If that's correct, what shoud I input when I search <kbd>--elisp "Silver Searcher"</kbd> for example?

**Comment by syohex** [comment] 2015-03-18 22:49
> But give me a chance to see why helm-ag--parse-query is needed. Is it intended to pass some options with search pattern?

Yes.

> If that's correct, what shoud I input when I search --elisp "Silver Searcher" for example?

`--elisp Silver Searcher`. You need not to wrap double quote.

**Comment by alpha22jp** [comment] 2015-03-18 23:25
I see, and thanks for adding tips on README.

**Comment by syohex** [comment] 2015-03-19 01:34
Please report me if you still have any issues.
Thanks for reporting the issue.

**Closed by syohex** 2015-03-19 01:34 UTC
