### ISSUE TITLE
ag and pt not working on a windows box

### ISSUE THREAD

**Issue by syl20bnr** [syohex/emacs-helm-ag#99] opened 2015-04-14 14:45 UTC
I recently unified the usage of ag, pt and ack under helm-ag in order to get the helm-ag-edit capability.
This does not seems to work on a windows box. I tracked the issue a bit and was able to take the output of `helm-ag--construct-command` verbatim and execute it on a cmd box and it works.

Do you have any insight about this issue, is it an output encoding issue ?

**Comment by syohex** [comment] 2015-04-15 10:15
Thanks for reporting, I'll check later.

NOTE: Now users have to install `pt` from source code. See also https://github.com/syohex/emacs-helm-ag/issues/46#issuecomment-93184259

**Comment by syohex** [comment] 2015-04-15 15:02
I confirmed that helm-ag does not work on Windows.
I suppose patch of https://github.com/monochromegane/the_platinum_searcher/pull/71 is not enough for Windows environment.

**Comment by syl20bnr** [comment] 2015-04-15 15:13
@ralesi What did you do in `helm-pt` to make it work on Windows ?

**Comment by syohex** [comment] 2015-04-16 03:03
I have sent PR https://github.com/monochromegane/the_platinum_searcher/pull/85.

**Comment by ralesi** [comment] 2015-04-16 15:37
For `helm-pt`, I just ran the command directly through a command process pipe, similar to `helm-do-grep`.  If we can get `helm-ag` working, it should be better.  @syohex, since there is a recommendation in the README to use `pt`, do you think we can separate out the `helm-sources` definition to change the modeline and the buffer name (i.e. instead of "*helm-ag*").

**Comment by syl20bnr** [comment] 2015-04-29 02:53
@syohex I tried your PR and it does not seem to work. I reinstalled `helm-pt` and it works, maybe you could explore the way `helm-pt` calls `pt` ?

**Comment by rorsach** [comment] 2015-05-17 06:41
Regarding ag not working inside Emacs, on Windows 64bit, I think I see the same issue handled over here:

https://github.com/Wilfred/ag.el/issues/26

It's easy to test. Open a command shell in emacs (M-x shell)

Works:
> ag sometext *.*

Fails:
> ag sometext


I wasn't able to get pt working using the same workaround (appending a ".")

**Comment by syohex** [comment] 2015-05-25 01:01
Sorry too late reply.
My patch was merged at 1.7.7. And I tried it on my Windows XP 32bit. `M-x helm-ag` works but `M-x helm-do-ag` does not work.

**Comment by Kludgy** [comment] 2015-05-28 22:23
So this still leaves the outstanding issue pointed out by @rorsach where both `ag` and `pt` pipes stall unless `.` is given as the root.

I don't understand what causes this in both cases but can definitely confirm it is still an issue on 64-bit versions of Windows.

What's the correct way to patch `helm-do-ag` to provide this additional parameter?  For instance, lacking familiarity with elisp I can hack a workaround by appending to `helm-ag--construct-do-ag-command`:

```
    (setq cmds (append cmds (list ".")))
```

This solves my issue. But how can I tidy this up?

**Comment by syohex** [comment] 2015-05-29 09:38
I have merged #112. I confirmed that both `helm-ag` and `helm-do-ag`(using `pt` instead of `ag`) works well on Windows with that change.

**Comment by syohex** [comment] 2015-06-01 02:32
@Kludgy Thanks for information. I don't know why, but path arguments must be specified on Windows when `helm-do-ag` executes. If omitting them, then `pt` process is killed immediately.

**Comment by syohex** [comment] 2015-06-01 02:33
Please try latest helm-ag and pt 1.7.7 or higher version.

**Comment by Kludgy** [comment] 2015-06-01 17:05
All is well with #112. Thank you kindly!

**Comment by rorsach** [comment] 2015-06-01 17:46
Validated working with pt 1.7.7 and #112, thank you.

**Comment by syohex** [comment] 2015-06-08 05:42
Please reopen the issue if there are any problems about `pt` on Windows.

**Closed by syohex** 2015-06-08 05:42 UTC

**Comment by syl20bnr** [comment] 2015-06-08 05:59
@syohex Nice work thank you :+1: 
P.S. nice catch @rorsach :-)
